routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->user()) {
        return redirect()->route('users.index');
    } else {
        return redirect()->route('login');
    }
});

// 권한 예외 처리
Route::get('/role', function() {
    Auth::logout();

    return view('role');
})->name('role');

Auth::routes();


Route::middleware(['auth', 'role'])->group( function () {


    Route::resource('users' , 'UserController');
    Route::get('/ajaxUserDeletes', 'UserController@UserDeletes')->name('UserDeletes');
    Route::get('/user_state_change', 'UserController@state_change')->name('users.state_change');
    Route::get('/user_find_id', 'UserController@find_id')->name('users.find.id');
    Route::get('/NonCertification', 'UserController@NonCertification')->name('users.NonCertification');

    Route::resource('faqs' , 'FaqController');
    Route::get('/faq_find_id', 'FaqController@find_id')->name('faqs.find.id');

    Route::resource('questions','QuestionController');
    Route::get('/question_find_id', 'QuestionController@find_id')->name('question.find.id');

    Route::resource('contactsus','ContactsusController')->only('index','destroy');
    Route::get('/contactsus_find_id', 'ContactsusController@find_id')->name('contactsu.find.id');

    Route::resources(['orders' => 'OrderController']);
    Route::resources(['goods' => 'GoodsController']);
    Route::resources(['option' => 'OptionController']);
    Route::resources(['cart' => 'CartController']);

    Route::get('/cart_find_id', 'CartController@find_id')->name('cart.find.id');

    Route::get('/checking', 'CartController@cart_state_1')->name('cart_state_1'); //확인중
    Route::get('/payment_waiting', 'CartController@cart_state_2')->name('cart_state_2'); //결제대기중
    Route::get('/payment_completed', 'CartController@cart_state_3')->name('cart_state_3'); //결제완료
    Route::get('/data_extraction', 'CartController@cart_state_4')->name('cart_state_4'); //데이터추출중
    Route::get('/data_completed', 'CartController@cart_state_5')->name('cart_state_5'); //데이터추출완료

    Route::get('/upload_waiting', 'CartController@option_state_1')->name('option_state_1'); //업로드대기
    Route::get('/upload_request', 'CartController@option_state_2')->name('option_state_2'); //업로드요청
    Route::get('/upload_completed', 'CartController@option_state_3')->name('option_state_3'); //업로드완료

    Route::get('/ajaxCartstate1update', 'CartController@state1update')->name('state1_update');  // 상태변경
    Route::post('/ajaxCartstate4fileupdate', 'CartController@state4fileupdate')->name('state4_fileupdate');  // 상태변경

    Route::get('/ajaxCartStateChange', 'CartController@stateChange')->name('carts_statechange');  // 상태변경
    Route::get('/ajaxOptionStateChange', 'OptionController@stateChange')->name('options_statechange');  // 상태변경
    Route::get('/ajaxTaxStateChange', 'OrderController@taxstateChange')->name('orders_taxstateChange');  // 상태변경

    Route::get('/file_download/{data_files}/{org_files}', 'CartController@file_download')->name('file_download'); // 파일 다운로드

    Route::get('ajaxDeleteOption', 'OptionController@DeleteOption')->name('DeleteOption'); // 옵션 삭제

    Route::get('/saleschart', 'StatisticsController@SalesChart')->name('saleschart');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
//    protected $fillable = [
//        'name', 'email', 'password','approved', 'approved_at'
//    ];

    protected $guarded = ['*','id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function format()
    {
        return [
            'id' => $this->id,
            'user_id' => $this->user_id,
            'password' => $this->password,
            'name' => $this->name,
            'phone' => $this->phone,
            'email' => $this->email,
            'title' => $this->title,
            'company_name' => $this->company_name,
            'taxes' => $this->taxes,
            'created_at' => $this->created_at,
            'approved' => $this->approved,
            'approved_at' => $this->approved_at,
            'last_update' => $this->updated_at->diffForHumans()
        ];
    }

    public function faqs()
    {
        return $this->hasMany(Faq::class);
    }

    public function taxes()
    {
        return $this->hasMany(Tax::class);
    }

    public function questions()
    {
        return $this->hasMany(Question::class)->orderBy('id','desc');
    }

    public function answers()
    {
        return $this->hasMany(Answer::class)->orderBy('id','desc');
    }

    public function carts()
    {
        return $this->hasMany(Cart::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SendMailable;
use App\Repositories\UserRepositoryInterface;
use App\Tax;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

class UserController extends Controller
{
    private $userRepository;

    public function __construct(UserRepositoryInterface $userRepository)
    {
        $this->userRepository = $userRepository;

        $this->route_name = Route::currentRouteName();
    }

    public function index(Request $request)
    {
        $route_name = $this->route_name;

        $users = $this->userRepository->all($request);



        $sch_key = $request->sch_key;
        $sch = $request->sch;
        $sch1 = $request->sch1;
        $sch2 = $request->sch2;

        $cnt = $users->total();

        return view('users.index', compact('users', 'sch_key','sch','sch1','sch2', 'route_name','cnt'));
    }

    public function show($id)
    {
        $users = $this->userRepository->findById($id);

        return view('users.show', compact('users'));
    }

    public function edit($id)
    {
        $users = $this->userRepository->findById($id);

        return view('users.edit', compact('users'));
    }

    public function update(Request $request, $id)
    {
        $info = $this->userRepository->findById($id);

        if (is_null($request->password)) {
            $request['password'] = $info['password'];
        } else {
            $request['password'] =  Hash::make($request->password);
        }

        $this->userRepository->update($request, $id);



        if ($request->tax_company_number) {

            $taxs = Tax::where('user_id', $info['id'])->get();

            $taxs_data['tax_company_number'] = $request['tax_company_number'];
            $taxs_data['tax_company_name'] = $request['tax_company_name'];
            $taxs_data['tax_name'] = $request['tax_name'];
            $taxs_data['tax_zipcode'] = $request['tax_zipcode'];
            $taxs_data['tax_addres_1'] = $request['tax_addres_1'];
            $taxs_data['tax_addres_2'] = $request['tax_addres_2'];
            $taxs_data['tax_img'] = $request['tax_img'];

            if ($request->tax_img) {
                $path = explode('/', $taxs_data['tax_img']->store('tax/'.$info['user_id']));
                $taxs_data['tax_img'] = $path[2];
            } else {
                $taxs_data['tax_img'] = $taxs[0]->tax_img;
            }

            Tax::where('user_id', $info['id'])->update($taxs_data);
        }


        return redirect()->route('users.index');
    }

    public function UserDeletes(Request $request)
    {
        $request_data = json_decode($request->data);


        $return_result = $this->userRepository->Deletes($request_data->ids);


        if (!$return_result) {
            $result['result'] = "error";
            $result['error_message'] = "등록되어 있는 데이터가 없습니다.";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        } else {
            $result['result'] = "success";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        }
        return $response;
    }


    public function destroy($id)
    {
        $this->userRepository->destory($id);

        return redirect()->route('users.index');
    }

    public function find_id(Request $request)
    {
        $request_data = json_decode($request->data);
        $user_info = $this->userRepository->findById($request_data->user_id);

        $result['result'] = "success";
        $result['user_info'] = $user_info;
        $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);

        return $response;
    }

    public function NonCertification(Request $request)
    {
        $route_name = $this->route_name;

        $users = $this->userRepository->NonCertification($request);

        $sch_key = $request->sch_key;
        $sch = $request->sch;
        $sch1 = $request->sch1;
        $sch2 = $request->sch2;

        $cnt = $users->total();

        return view('users.index', compact('users', 'sch_key','sch','sch1','sch2', 'route_name', 'cnt'));
    }

    public function state_change(Request $request)
    {
        $request_data = json_decode($request->data);

        if ($request_data->states == "1") {
            $user_info = $this->userRepository->findById($request_data->user_id);

            Mail::to($user_info['email'])->send(new SendMailable($user_info));
        }

        $return_result = $this->userRepository->StateChange($request_data);

        if (!$return_result) {
            $result['result'] = "error";
            $result['error_message'] = "등록되어 있는 데이터가 없습니다.";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        } else {
            $result['result'] = "success";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        }

        return $response;
    }
}

resources/views/users/edit.blade.php
@extends('layouts.backoffice')

@section('content')

    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i> </div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('users.update', $users['user_id']) }}">
                                @csrf
                                @method('PUT')
                                <div class="form-group row">
                                    <div class="col">
                                        <label>이름</label>
                                        <input class="form-control" type="text" placeholder="Name" name="name" value="{{ $users['name'] }}" required autofocus>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col">
                                        <label>Email</label>
                                        <input class="form-control" type="text" placeholder="Email" name="email" value="{{ $users['email'] }}" required autofocus>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col">
                                        <label>승인여부</label>
                                        <select class="form-control" name="approved">
                                            <option value="0" {{ $users['approved'] == '0' ? 'selected' : '' }} >비승인</option>
                                            <option value="1" {{ $users['approved'] == '1' ? 'selected' : '' }} >승인</option>
                                        </select>
                                    </div>
                                </div>

                                <button class="btn btn-block btn-success" type="submit">저장</button>
                                <a href="{{ route('users.index') }}" class="btn btn-block btn-primary">뒤로가기</a>
                            </form>
                        </div>
                    </div>
                </div>

                @if (!$users['tax']->isEmpty())
                    <div class="col-sm-6">
                        <div class="card">
                            <div class="card-header"><strong>계산서정보</strong> <small></small></div>
                            <div class="card-body">

                                <div class="form-group">
                                    <label for="company">사업자등록번호</label>
                                    <input class="form-control" value=""  type="text" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="vat">업체명(법인명)</label>
                                    <input class="form-control" value="{{$users['tax'][0]['tax_company_name']}}" type="text" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="street">대표자명</label>
                                    <input class="form-control"  value="{{$users['tax'][0]['tax_name']}}" type="text" placeholder="">
                                </div>
                                <div class="row">
                                    <div class="form-group col-sm-8">
                                        <label for="city">주소</label>
                                        <input class="form-control" value="{{$users['tax'][0]['tax_addres_1']}}" type="text" placeholder="">
                                    </div>
                                    <div class="form-group col-sm-4">
                                        <label for="postal-code">우편번호</label>
                                        <input class="form-control" value="{{$users['tax'][0]['tax_zipcode']}}" type="text" placeholder="">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" value="{{$users['tax'][0]['tax_addres_2']}}"  type="text" placeholder="">
                                </div>
                                <div class="form-group">
                                    <label for="country">사업자등록증</label><br />
                                    {{ $users['tax'][0]['tax_img'] }}
                                </div>

                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>



@endsection

resources/views/users/show.blade.php
@extends('layouts.backoffice')

@section('content')
<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i> </div>
                            <div class="card-body">
                                <h5>이름:</h5>
                                <p> {{ $users['name'] }}</p>
                                <h5>Email:</h5>
                                <p> {{ $users['email'] }}</p>
                                <h5>가입일자:</h5>
                                <p> {{ $users['created_at'] }}</p>
                                <h5> 승인여부: </h5>
                                <p>
                                    @if ( $users['approved'])
                                        <span class="badge badge-pill badge-warning">
                                          인증
                                        </span>
                                    @else
                                        <span class="badge badge-pill badge-secondary">
                                          비인증
                                        </span>
                                    @endif
                                </p>
                                <h5>Approved_at:</h5>
                                <p> {{ $users['approved_at'] }}</p>

                                <a href="{{ route('users.index') }}" class="btn btn-block btn-primary">Return</a>
                            </div>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection