routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->user()) {
        return redirect()->route('users.index');
    } else {
        return redirect()->route('login');
    }
});

// 권한 예외 처리
Route::get('/role', function() {
    Auth::logout();

    return view('role');
})->name('role');

Auth::routes();


Route::middleware(['auth', 'role'])->group( function () {


    Route::resource('users' , 'UserController');
    Route::get('/ajaxUserDeletes', 'UserController@UserDeletes')->name('UserDeletes');
    Route::get('/user_state_change', 'UserController@state_change')->name('users.state_change');
    Route::get('/user_find_id', 'UserController@find_id')->name('users.find.id');
    Route::get('/NonCertification', 'UserController@NonCertification')->name('users.NonCertification');

    Route::resource('faqs' , 'FaqController');
    Route::get('/faq_find_id', 'FaqController@find_id')->name('faqs.find.id');

    Route::resource('questions','QuestionController');
    Route::get('/question_find_id', 'QuestionController@find_id')->name('question.find.id');

    Route::resource('contactsus','ContactsusController')->only('index','destroy');
    Route::get('/contactsus_find_id', 'ContactsusController@find_id')->name('contactsu.find.id');

    Route::resources(['orders' => 'OrderController']);
    Route::resources(['goods' => 'GoodsController']);
    Route::resources(['option' => 'OptionController']);
    Route::resources(['cart' => 'CartController']);

    Route::get('/cart_find_id', 'CartController@find_id')->name('cart.find.id');

    Route::get('/checking', 'CartController@cart_state_1')->name('cart_state_1'); //확인중
    Route::get('/payment_waiting', 'CartController@cart_state_2')->name('cart_state_2'); //결제대기중
    Route::get('/payment_completed', 'CartController@cart_state_3')->name('cart_state_3'); //결제완료
    Route::get('/data_extraction', 'CartController@cart_state_4')->name('cart_state_4'); //데이터추출중
    Route::get('/data_completed', 'CartController@cart_state_5')->name('cart_state_5'); //데이터추출완료

    Route::get('/upload_waiting', 'CartController@option_state_1')->name('option_state_1'); //업로드대기
    Route::get('/upload_request', 'CartController@option_state_2')->name('option_state_2'); //업로드요청
    Route::get('/upload_completed', 'CartController@option_state_3')->name('option_state_3'); //업로드완료

    Route::get('/ajaxCartstate1update', 'CartController@state1update')->name('state1_update');  // 상태변경
    Route::post('/ajaxCartstate4fileupdate', 'CartController@state4fileupdate')->name('state4_fileupdate');  // 상태변경

    Route::get('/ajaxCartStateChange', 'CartController@stateChange')->name('carts_statechange');  // 상태변경
    Route::get('/ajaxOptionStateChange', 'OptionController@stateChange')->name('options_statechange');  // 상태변경
    Route::get('/ajaxTaxStateChange', 'OrderController@taxstateChange')->name('orders_taxstateChange');  // 상태변경

    Route::get('/file_download/{data_files}/{org_files}', 'CartController@file_download')->name('file_download'); // 파일 다운로드

    Route::get('ajaxDeleteOption', 'OptionController@DeleteOption')->name('DeleteOption'); // 옵션 삭제

    Route::get('/saleschart', 'StatisticsController@SalesChart')->name('saleschart');

});

app/Goods.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Goods extends Model
{
    protected $guarded = ['*','id'];

    public function format()
    {
        return [
            'goods_id' => $this->id,
            'advertiser' => $this->advertiser,
            'data_types' => $this->data_types,
            'data_target' => $this->data_target,
            'data_name' => $this->data_name,
            'data_category' => $this->data_category,
            'data_content' => $this->data_content,
            'data_count' => $this->data_count,
            'buy_price' => $this->buy_price,
            'expiration_date' => $this->expiration_date,
            'cart' => $this->cart,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at
        ];
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function cart()
    {
        return $this->belongsTo(Cart::class, 'id');
    }

    public function getMarkPriceAttribute()
    {
        return number_format($this->buy_price);
    }
}

app/Http/Controllers/GoodsController.php
<?php

namespace App\Http\Controllers;

use App\Goods;
use App\Repositories\CartRepositoryInterface;
use App\Repositories\GoodsRepositoryInterface;
use Illuminate\Http\Request;

class GoodsController extends Controller
{
    private $cartRepository;
    private $goodsRepository;

    public function __construct(CartRepositoryInterface $cartRepository,
                                GoodsRepositoryInterface $goodsRepository)
    {
        $this->cartRepository = $cartRepository;
        $this->goodsRepository = $goodsRepository;
    }

    public function index()
    {
        $goods = $this->goodsRepository->all();

        return view('goods.index', compact('goods'));
    }


    public function edit($id)
    {
        $goods = $this->goodsRepository->findById($id);

        return view('goods.edit', compact('goods'));
    }

    public function update(Request $request, $id)
    {
        $this->goodsRepository->update($request, $id);
        $this->cartRepository->updateState($request, $id);

        return redirect()->route('goods.index');
    }

}

resources/views/goods/edit.blade.php
@extends('layouts.backoffice')

@prepend('scripts')
    $(function() {
        $("#expiration_date").datepicker({
            dateFormat: 'yy-mm-dd' //Input Display Format 변경
            ,showOtherMonths: true //빈 공간에 현재월의 앞뒤월의 날짜를 표시
            ,showMonthAfterYear:true //년도 먼저 나오고, 뒤에 월 표시
            ,changeYear: true //콤보박스에서 년 선택 가능
            ,changeMonth: true //콤보박스에서 월 선택 가능
            ,buttonImageOnly: true //기본 버튼의 회색 부분을 없애고, 이미지만 보이게 함
            ,buttonText: "선택" //버튼에 마우스 갖다 댔을 때 표시되는 텍스트
            ,yearSuffix: "년" //달력의 년도 부분 뒤에 붙는 텍스트
            ,monthNamesShort: ['1','2','3','4','5','6','7','8','9','10','11','12'] //달력의 월 부분 텍스트
            ,monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'] //달력의 월 부분 Tooltip 텍스트
            ,dayNamesMin: ['일','월','화','수','목','금','토'] //달력의 요일 부분 텍스트
            ,dayNames: ['일요일','월요일','화요일','수요일','목요일','금요일','토요일'] //달력의 요일 부분 Tooltip 텍스트
            ,minDate: new Date() //최소 선택일자(-1D:하루전, -1M:한달전, -1Y:일년전)
        });
    });
@endprepend

@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i>
                            <div class="card-body">
                                <h5>광고주:</h5>
                                <p> {{ $goods['advertiser'] }}</p>
                                <h5>데이터명:</h5>
                                <p> {{ $goods['data_name'] }}</p>
                                <h5>데이터항목:</h5>
                                <p> {{ $goods['data_category'] }}</p>
                                <h5>설명:</h5>
                                <p> {!! nl2br(e($goods['data_content'] )) !!} </p>
                                <form method="POST" action="{{ route('goods.update', $goods['goods_id']) }}">
                                    @csrf
                                    @method('PUT')

                                    <div class="form-group row">
                                        <div class="col">
                                            <label>상태</label>
                                            <select class="form-control" name="state">
                                                <option value="1" {{ $goods['cart']->state == '1' ? 'selected' : '' }} >결제대기중</option>
                                                <option value="2" {{ $goods['cart']->state == '2' ? 'selected' : '' }} >결제완료</option>
                                                <option value="3" {{ $goods['cart']->state == '3' ? 'selected' : '' }} >데이터추출완료</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col">
                                            <label>데이터 수</label>
                                            <input class="form-control" type="text" placeholder="data_count" name="data_count" value="{{ $goods['data_count'] }}"  autofocus>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col">
                                            <label>데이터 가격</label>
                                            <input class="form-control" type="text" placeholder="buy_price" name="buy_price" value="{{ $goods['buy_price'] }}"  autofocus>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col">
                                            <label>유효기간</label>
                                            <input class="form-control" type="text" placeholder="expiration_date" id="expiration_date" name="expiration_date"  value="{{ $goods['expiration_date'] }}"  autofocus>
                                        </div>
                                    </div>

                                    <button class="btn btn-block btn-success" type="submit">Save</button>
                                    <a href="" class="btn btn-block btn-primary">Return</a>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



@endsection

resources/views/goods/index.blade.php
@extends('layouts.backoffice')

@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i>
                            <div class="card-body">
                                <table class="table table-responsive-sm table-striped">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>광고주</th>
                                        <th>데이터명</th>
                                        <th>데이터 수</th>
                                        <th>이름</th>
                                        <th>데이터가격</th>
                                        <th>상태</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($goods as $good)
                                        <tr>
                                            <td>{{ $good->id }}</td>
                                            <td>{{ $good->advertiser }}</td>
                                            <td>{{ $good->data_name }}</td>
                                            <td>{{ $good->data_count }}</td>
                                            <td>{{ $good->user->name }}</td>
                                            <td>{{ $good->mark_price }} 원</td>
                                            <td>
                                                @if ($good->cart->state === 1)
                                                    결제대기중
                                                @elseif ($good->cart->state === 2)
                                                    결제완료
                                                @elseif ($good->cart->state === 3)
                                                    데이터 추출완료
                                                @endif
                                            </td>
                                            <td>
                                                <a href="{{ route('goods.edit', $good->id) }}" class="btn btn-block btn-primary">Edit</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                {{ $goods->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection