routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->user()) {
        return redirect()->route('users.index');
    } else {
        return redirect()->route('login');
    }
});

// 권한 예외 처리
Route::get('/role', function() {
    Auth::logout();

    return view('role');
})->name('role');

Auth::routes();


Route::middleware(['auth', 'role'])->group( function () {


    Route::resource('users' , 'UserController');
    Route::get('/ajaxUserDeletes', 'UserController@UserDeletes')->name('UserDeletes');
    Route::get('/user_state_change', 'UserController@state_change')->name('users.state_change');
    Route::get('/user_find_id', 'UserController@find_id')->name('users.find.id');
    Route::get('/NonCertification', 'UserController@NonCertification')->name('users.NonCertification');

    Route::resource('faqs' , 'FaqController');
    Route::get('/faq_find_id', 'FaqController@find_id')->name('faqs.find.id');

    Route::resource('questions','QuestionController');
    Route::get('/question_find_id', 'QuestionController@find_id')->name('question.find.id');

    Route::resource('contactsus','ContactsusController')->only('index','destroy');
    Route::get('/contactsus_find_id', 'ContactsusController@find_id')->name('contactsu.find.id');

    Route::resources(['orders' => 'OrderController']);
    Route::resources(['goods' => 'GoodsController']);
    Route::resources(['option' => 'OptionController']);
    Route::resources(['cart' => 'CartController']);

    Route::get('/cart_find_id', 'CartController@find_id')->name('cart.find.id');

    Route::get('/checking', 'CartController@cart_state_1')->name('cart_state_1'); //확인중
    Route::get('/payment_waiting', 'CartController@cart_state_2')->name('cart_state_2'); //결제대기중
    Route::get('/payment_completed', 'CartController@cart_state_3')->name('cart_state_3'); //결제완료
    Route::get('/data_extraction', 'CartController@cart_state_4')->name('cart_state_4'); //데이터추출중
    Route::get('/data_completed', 'CartController@cart_state_5')->name('cart_state_5'); //데이터추출완료

    Route::get('/upload_waiting', 'CartController@option_state_1')->name('option_state_1'); //업로드대기
    Route::get('/upload_request', 'CartController@option_state_2')->name('option_state_2'); //업로드요청
    Route::get('/upload_completed', 'CartController@option_state_3')->name('option_state_3'); //업로드완료

    Route::get('/ajaxCartstate1update', 'CartController@state1update')->name('state1_update');  // 상태변경
    Route::post('/ajaxCartstate4fileupdate', 'CartController@state4fileupdate')->name('state4_fileupdate');  // 상태변경

    Route::get('/ajaxCartStateChange', 'CartController@stateChange')->name('carts_statechange');  // 상태변경
    Route::get('/ajaxOptionStateChange', 'OptionController@stateChange')->name('options_statechange');  // 상태변경
    Route::get('/ajaxTaxStateChange', 'OrderController@taxstateChange')->name('orders_taxstateChange');  // 상태변경

    Route::get('/file_download/{data_files}/{org_files}', 'CartController@file_download')->name('file_download'); // 파일 다운로드

    Route::get('ajaxDeleteOption', 'OptionController@DeleteOption')->name('DeleteOption'); // 옵션 삭제

    Route::get('/saleschart', 'StatisticsController@SalesChart')->name('saleschart');

});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $appends = ['new_date'];

    protected $fillable = [
        'title', 'content',
    ];

    protected $guarded = [];

    public function format()
    {
        return [
            'question_id' => $this->id,
            'id' => $this->user->user_id,
            'name' => $this->name,
            'title' => $this->title,
            'content' => $this->content,
            'phone' => $this->phone,
            'email' => $this->email,
            'last_update' => $this->updated_at->diffForHumans(),
            'answers' => $this->answers,
        ];
    }

    public function getNewDateAttribute()
    {
        $REG_DATE = strtotime($this->updated_at);
        $REG_TIME = time();
        $TIME = 60*60*24;

        if ( ($REG_TIME-$REG_DATE) < $TIME ) {
            $new="1";
        }else{
            $new="";
        }

        return $new;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }



    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\QuestionRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

class QuestionController extends Controller
{
    private $questionRepository;

    public function __construct(QuestionRepositoryInterface $questionRepository)
    {
        $this->questionRepository = $questionRepository;

        $this->route_name = Route::currentRouteName();
    }

    public function index(Request $request)
    {

        $route_name = $this->route_name;

        $questions = $this->questionRepository->all($request);

        $sch_key = $request->sch_key;
        $sch = $request->sch;
        $sch1 = $request->sch1;
        $sch2 = $request->sch2;

        $cnt = $questions->total();

        return view('questions.index', compact('questions','sch_key','sch','sch1','sch2', 'route_name', 'cnt'));
    }

    public function create()
    {
        return view('questions.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'content' => 'required',
        ]);
        $this->questionRepository->create($validatedData);

        return redirect()->route('questions.index');
    }

    public function show($id)
    {
        $question = $this->questionRepository->findById($id);

        return view('questions.show', compact('question'));
    }

    public function edit($id)
    {
        $question = $this->questionRepository->findById($id);

        return view('questions.edit', compact('question'));
    }

    public function update(Request $request, $id)
    {
        $this->questionRepository->answer_update($request, $id);

        return redirect()->route('questions.index');
    }

    public function destroy($id)
    {
        $this->questionRepository->destory($id);

        return redirect()->route('questions.index');
    }

    public function find_id(Request $request)
    {
        $request_data = json_decode($request->data);
        $question_info = $this->questionRepository->findById($request_data->question_id);

        $result['result'] = "success";
        $result['question_info'] = $question_info;
        $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);

        return $response;
    }
}

resources/views/questions/create.blade.php
@extends('layouts.backoffice')

@section('content')

    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i>
                        <div class="card-body">
                            <form method="POST" action="{{ route('faqs.store') }}">
                                @csrf

                                <div class="form-group row">
                                    <div class="col">
                                        <label>제목</label>
                                        <input class="form-control" type="text" placeholder="Title" name="title" value="" required autofocus>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col">
                                        <label>내용</label>
                                        <textarea class="form-control" type="text" placeholder="Email" name="content"  required autofocus></textarea>
                                    </div>
                                </div>

                                <button class="btn btn-block btn-success" type="submit">Save</button>
                                <a href="{{ route('faqs.index') }}" class="btn btn-block btn-primary">Return</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/questions/edit.blade.php
@extends('layouts.backoffice')

@section('content')

    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i></div>
                        <div class="card-body">
                            <form method="POST" action="{{ route('questions.update', $question['question_id']) }}">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="question_id" value="{{ $question['question_id'] }}">

                                <h5>작성자:</h5>
                                <p> {{ $question['name'] }}</p>
                                <h5>제목:</h5>
                                <p> {{ $question['title'] }}</p>
                                <h5>내용:</h5>
                                <p> {{ $question['content'] }}</p>
                                <h5>연락처:</h5>
                                <p> {{ $question['phone'] }}</p>
                                <h5>email:</h5>
                                <p> {{ $question['email'] }}</p>
                                <h5>답변:</h5>
                                <p>
                                    <textarea class="form-control" type="text" placeholder="answers" name="content"  required autofocus>
                                        @if ($question['answers']->count() >0)
                                            {{ $question['answers'][0]['content'] }}
                                        @endif
                                    </textarea>
                                </p>

                                <button class="btn btn-block btn-success" type="submit">저장</button>
                                <a href="{{ route('questions.index') }}" class="btn btn-block btn-primary">뒤로가기</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/questions/show.blade.php
@extends('layouts.backoffice')

@section('content')
<div class="container-fluid">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                <div class="card">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i> </div>
                    <div class="card-body">
                        <h5>작성자:</h5>
                        <p> {{ $question['name'] }}</p>
                        <h5>제목:</h5>
                        <p> {{ $question['title'] }}</p>
                        <h5>내용:</h5>
                        <p> {{ $question['content'] }}</p>

                        @if ($question['answers']->count() >0)
                            <h5>답변:</h5>
                            <p> {{ $question['answers'][0]['content'] }}</p>
                        @endif
                        <a href="{{ route('questions.index') }}" class="btn btn-block btn-primary">Return</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection