routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (auth()->user()) {
        return redirect()->route('users.index');
    } else {
        return redirect()->route('login');
    }
});

// 권한 예외 처리
Route::get('/role', function() {
    Auth::logout();

    return view('role');
})->name('role');

Auth::routes();


Route::middleware(['auth', 'role'])->group( function () {


    Route::resource('users' , 'UserController');
    Route::get('/ajaxUserDeletes', 'UserController@UserDeletes')->name('UserDeletes');
    Route::get('/user_state_change', 'UserController@state_change')->name('users.state_change');
    Route::get('/user_find_id', 'UserController@find_id')->name('users.find.id');
    Route::get('/NonCertification', 'UserController@NonCertification')->name('users.NonCertification');

    Route::resource('faqs' , 'FaqController');
    Route::get('/faq_find_id', 'FaqController@find_id')->name('faqs.find.id');

    Route::resource('questions','QuestionController');
    Route::get('/question_find_id', 'QuestionController@find_id')->name('question.find.id');

    Route::resource('contactsus','ContactsusController')->only('index','destroy');
    Route::get('/contactsus_find_id', 'ContactsusController@find_id')->name('contactsu.find.id');

    Route::resources(['orders' => 'OrderController']);
    Route::resources(['goods' => 'GoodsController']);
    Route::resources(['option' => 'OptionController']);
    Route::resources(['cart' => 'CartController']);

    Route::get('/cart_find_id', 'CartController@find_id')->name('cart.find.id');

    Route::get('/checking', 'CartController@cart_state_1')->name('cart_state_1'); //확인중
    Route::get('/payment_waiting', 'CartController@cart_state_2')->name('cart_state_2'); //결제대기중
    Route::get('/payment_completed', 'CartController@cart_state_3')->name('cart_state_3'); //결제완료
    Route::get('/data_extraction', 'CartController@cart_state_4')->name('cart_state_4'); //데이터추출중
    Route::get('/data_completed', 'CartController@cart_state_5')->name('cart_state_5'); //데이터추출완료

    Route::get('/upload_waiting', 'CartController@option_state_1')->name('option_state_1'); //업로드대기
    Route::get('/upload_request', 'CartController@option_state_2')->name('option_state_2'); //업로드요청
    Route::get('/upload_completed', 'CartController@option_state_3')->name('option_state_3'); //업로드완료

    Route::get('/ajaxCartstate1update', 'CartController@state1update')->name('state1_update');  // 상태변경
    Route::post('/ajaxCartstate4fileupdate', 'CartController@state4fileupdate')->name('state4_fileupdate');  // 상태변경

    Route::get('/ajaxCartStateChange', 'CartController@stateChange')->name('carts_statechange');  // 상태변경
    Route::get('/ajaxOptionStateChange', 'OptionController@stateChange')->name('options_statechange');  // 상태변경
    Route::get('/ajaxTaxStateChange', 'OrderController@taxstateChange')->name('orders_taxstateChange');  // 상태변경

    Route::get('/file_download/{data_files}/{org_files}', 'CartController@file_download')->name('file_download'); // 파일 다운로드

    Route::get('ajaxDeleteOption', 'OptionController@DeleteOption')->name('DeleteOption'); // 옵션 삭제

    Route::get('/saleschart', 'StatisticsController@SalesChart')->name('saleschart');

});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Parsedown;

class Order extends Model
{
    protected $appends = ['new_date'];

    CONST STATE_1 = 0;      // 결제전
    CONST STATE_2 = 1;      // 결제완료

    CONST TAX_STATE_1 = 1;  // 계산서 요청가능 (미발행)
    CONST TAX_STATE_2 = 2;  // 계산서 요청신청 (확인중)
    CONST TAX_STATE_3 = 3;  // 계산서 신청완료 (발행)

    protected $guarded = ['*','id'];

    public function format()
    {
        return [
            'order_id' => $this->id,
            'user_id' => $this->user,
            'payment_id' => $this->payment_returns,
            'order_no' => $this->carts,
            'order_name' => $this->order_name,
            'goods_info' => $this->goods_info,
            'state' => $this->state,
            'tax_state' => $this->tax_state,
            'total_count' => $this->total_count,
            'total_price' => $this->total_price,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at
        ];
    }

    public function getNewDateAttribute()
    {
        $REG_DATE = strtotime($this->updated_at);
        $REG_TIME = time();
        $TIME = 60*60*24;

        if ( ($REG_TIME-$REG_DATE) < $TIME ) {
            $new="1";
        }else{
            $new="";
        }

        return $new;
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function payment_returns()
    {
        return $this->belongsTo(Payment_return::class, 'payment_id');
    }

    public function carts()
    {
        return $this->belongsTo(Cart::class, 'order_no', 'order_no');
    }

    public function getContentHtmlAttribute()
    {
        return Parsedown::instance()->text($this->data_content);
    }

    public function getMarkPriceAttribute()
    {
        return number_format($this->buy_price);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\OrderRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

class OrderController extends Controller
{
    private $orderRepository;
    private $route_name;

    public function __construct(OrderRepositoryInterface $orderRepository)
    {
        $this->orderRepository = $orderRepository;

        $this->route_name = Route::currentRouteName();
    }

    public function index(Request $request)
    {
        $route_name = $this->route_name;

        $orders = $this->orderRepository->all($request);

       // dd($orders[0]->user->user_id);

        $sch_key = $request->sch_key;
        $sch = $request->sch;
        $sch1 = $request->sch1;
        $sch2 = $request->sch2;

        return view('orders.index', compact('orders', 'sch_key','sch','sch1','sch2', 'route_name'));
    }

    public function taxstateChange(Request $request)
    {
        $request_data = json_decode($request->data);
        $return_result = $this->orderRepository->taxstateChange($request_data);

        if (!$return_result) {
            $result['result'] = "error";
            $result['error_message'] = "등록되어 있는 계산서가 없습니다.";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        } else {
            $result['result'] = "success";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        }

        return $response;

    }

}

resources/views/orders/edit.blade.php
@extends('layouts.backoffice')

@prepend('scripts')
    $(function() {
        $("#expiration_date").datepicker({
            dateFormat: 'yy-mm-dd' //Input Display Format 변경
            ,showOtherMonths: true //빈 공간에 현재월의 앞뒤월의 날짜를 표시
            ,showMonthAfterYear:true //년도 먼저 나오고, 뒤에 월 표시
            ,changeYear: true //콤보박스에서 년 선택 가능
            ,changeMonth: true //콤보박스에서 월 선택 가능
            ,buttonImageOnly: true //기본 버튼의 회색 부분을 없애고, 이미지만 보이게 함
            ,buttonText: "선택" //버튼에 마우스 갖다 댔을 때 표시되는 텍스트
            ,yearSuffix: "년" //달력의 년도 부분 뒤에 붙는 텍스트
            ,monthNamesShort: ['1','2','3','4','5','6','7','8','9','10','11','12'] //달력의 월 부분 텍스트
            ,monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'] //달력의 월 부분 Tooltip 텍스트
            ,dayNamesMin: ['일','월','화','수','목','금','토'] //달력의 요일 부분 텍스트
            ,dayNames: ['일요일','월요일','화요일','수요일','목요일','금요일','토요일'] //달력의 요일 부분 Tooltip 텍스트
            ,minDate: new Date() //최소 선택일자(-1D:하루전, -1M:한달전, -1Y:일년전)
        });
    });
@endprepend

@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i>
                            <div class="card-body">
                                <h5>광고주:</h5>
                                <p> {{ $order['advertiser'] }}</p>
                                <h5>플랫폼 유형:</h5>
                                <p> {{ $order['data_types'] }}</p>
                                <h5>데이터명:</h5>
                                <p> {{ $order['data_name'] }}</p>
                                <h5>데이터항목:</h5>
                                <p> {{ $order['data_category'] }}</p>
                                <h5>설명:</h5>
                                <p> {!! $order['data_content'] !!} </p>
                                <form method="POST" action="{{ route('orders.update', $order['order_id']) }}">
                                    @csrf
                                    @method('PUT')

                                    <div class="form-group row">
                                        <div class="col">
                                            <label>상태</label>
                                            <select class="form-control" name="state">
                                                <option value="1" {{ $order['state'] == '1' ? 'selected' : '' }} >요청중</option>
                                                <option value="2" {{ $order['state'] == '2' ? 'selected' : '' }} >추출중</option>
                                                <option value="3" {{ $order['state'] == '3' ? 'selected' : '' }} >승인요청</option>
                                                <option value="5" {{ $order['state'] == '4' ? 'selected' : '' }} >결제완료</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col">
                                            <label>데이터 수</label>
                                            <input class="form-control" type="text" placeholder="data_count" name="data_count" value="{{ $order['data_count'] }}"  autofocus>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <div class="col">
                                            <label>데이터 가격</label>
                                            <input class="form-control" type="text" placeholder="buy_price" name="buy_price" value="{{ $order['buy_price'] }}"  autofocus>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col">
                                            <label>유효기간</label>
                                            <input class="form-control" type="text" placeholder="expiration_date" id="expiration_date" name="expiration_date"  value="{{ $order['expiration_date'] }}"  autofocus>
                                        </div>
                                    </div>

                                    <button class="btn btn-block btn-success" type="submit">Save</button>
                                    <a href="{{ route('orders.index') }}" class="btn btn-block btn-primary">Return</a>
                                </form>

                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



@endsection

resources/views/orders/index.blade.php
@extends('layouts.backoffice')

@prepend('scripts')
    <script>
        $(function() {
            $(".sch1, .sch2").datepicker({
                dateFormat: 'yy-mm-dd' //Input Display Format 변경
                ,showOtherMonths: true //빈 공간에 현재월의 앞뒤월의 날짜를 표시
                ,showMonthAfterYear:true //년도 먼저 나오고, 뒤에 월 표시
                ,changeYear: true //콤보박스에서 년 선택 가능
                ,changeMonth: true //콤보박스에서 월 선택 가능
                ,buttonImageOnly: true //기본 버튼의 회색 부분을 없애고, 이미지만 보이게 함
                ,buttonText: "선택" //버튼에 마우스 갖다 댔을 때 표시되는 텍스트
                ,yearSuffix: "년" //달력의 년도 부분 뒤에 붙는 텍스트
                ,monthNamesShort: ['1','2','3','4','5','6','7','8','9','10','11','12'] //달력의 월 부분 텍스트
                ,monthNames: ['1월','2월','3월','4월','5월','6월','7월','8월','9월','10월','11월','12월'] //달력의 월 부분 Tooltip 텍스트
                ,dayNamesMin: ['일','월','화','수','목','금','토'] //달력의 요일 부분 텍스트
                ,dayNames: ['일요일','월요일','화요일','수요일','목요일','금요일','토요일'] //달력의 요일 부분 Tooltip 텍스트
            });

            $("select[name=sch_key]").change(function() {
                console.log($(this).val());
                if ($(this).val() == "created_at") {
                    $("#input").css("display", "none");
                    $("#input1-group1").css("display", "block");
                    $("#input_span").css("display", "block");
                    $("#input2-group2").css("display", "block");
                } else {
                    $("#input").css("display", "block");
                    $("#input1-group1").css("display", "none");
                    $("#input_span").css("display", "none");
                    $("#input2-group2").css("display", "none");
                }
            });

            $("select[name=tax_state]").change(function() {

                var data = new Object();
                data.order_id = $(this).data("order_id");
                data.tax_state = $(this).val();
                var jsonData = JSON.stringify(data);

                $.ajax({
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    url: "{{ route('orders_taxstateChange') }}",
                    method: "POST",
                    dataType: "json",
                    data: {'data': jsonData},
                    success: function (data) {
                        var JSONArray = JSON.parse(JSON.stringify(data));

                        if (JSONArray['result'] == "success") {
                            alert('수정 되었습니다.');
                            location.reload();
                        } else if (JSONArray['result'] == "error") {
                            alert(JSONArray['error_message']);
                        };
                    },
                    error: function () {
                        alert("Error while getting results");
                    }
                });
            });
        });
    </script>
@endprepend

@section('content')
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i>
                            <div class="card-body">
                                <table class="table table-responsive-sm table-striped">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>
                                            <div>User ID</div>
                                            <div>User 이름</div>
                                        </th>
                                        <th>주문번호</th>
                                        <th>구매내역</th>
                                        <th>구매날짜</th>
                                        <th>구매가격</th>
                                        <th>결제방식</th>
                                        <th>계산서 발행여부</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($orders as $order)
                                        <tr>
                                            <td>
                                                {{ $order->id }}
                                                @if ($order->new_date == '1')
                                                    <img src="/assets/img/new.png" width="15" height="15" >
                                                @endif
                                            </td>
                                            <td>
                                                <div>
                                                    <span>User ID :</span>
                                                    @if ($order->user)
                                                        <a href="/users?sch_key=user_id&sch={{ $order->user->user_id }}"&sch1=&sch2=>{{ $order->user->user_id }}</a>
                                                    @endif
                                                </div>
                                                <div>
                                                    <span>User 이름 :</span>
                                                    @if ($order->user)
                                                        <a href="/users?sch_key=name&sch={{ $order->user->name }}"&sch1=&sch2=>{{ $order->user->name }}</a>
                                                    @endif
                                                </div>
                                            </td>

                                            <td>{{ $order->order_no }}</td>
                                            <td>{{ $order->order_name }}</td>
                                            <td>{{ $order->created_at }}</td>
                                            <td>{{ number_format($order->total_price) }}</td>
                                            <td>신용카드</td>
                                            <td>
                                                <select name="tax_state" data-order_id="{{ $order->id }}">
                                                    <option value="1" {{ $order->tax_state == '1' ? 'selected' : '' }}>계산서신청하기</option>
                                                    <option value="2" {{ $order->tax_state == '2' ? 'selected' : '' }}>확인중</option>
                                                    <option value="3" {{ $order->tax_state == '3' ? 'selected' : '' }}>계산서발급완료</option>
                                                </select>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                                <div class="col-sm-4 " style="margin: auto">
                                    <form class="form-horizontal" action="{{ route($route_name) }}" method="GET">
                                        <div class="form-group row">
                                            <div class="col-md-12">
                                                <div class="input-group">
                                                    <select name="sch_key">
                                                        <option value="order_no" {{ ($sch_key=="order_no") ? "selected" : ""  }}  >주문번호</option>
                                                        <option value="order_name" {{ ($sch_key=="order_name") ? "selected" : ""  }} >구매내역</option>
                                                        <option value="created_at" {{ ($sch_key=="created_at") ? "selected" : ""  }} >구매날짜</option>
                                                    </select>&nbsp;
                                                    <input class="form-control" id="input" type="text" name="sch" value="{{ $sch }}" placeholder="검색어" autocomplete="sch" style="display: {{ ($sch_key=="created_at") ? "none;" : "block;"  }}"  >
                                                    <input class="form-control sch1" id="input1-group1" type="text" name="sch1" value="{{ $sch1 }}" placeholder="검색어" autocomplete="sch" style="display: {{ ($sch_key=="created_at") ? "block;" : "none;"  }}" >
                                                    &nbsp;<span id="input_span" style="display: {{ ($sch_key=="created_at") ? "block;" : "none;"  }}">~</span>&nbsp;
                                                    <input class="form-control sch2" id="input2-group2" type="text" name="sch2" value="{{ $sch2 }}" placeholder="검색어" autocomplete="sch" style="display: {{ ($sch_key=="created_at") ? "block;" : "none;"  }}" >
                                                    <span class="input-group-append">
                                                        <button class="btn btn-facebook" type="submit" style="z-index: 0;">검색</button>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                {{ $orders->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection